name: Java CI
on: [push, pull_request]
  
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: action/setup-java@v1
          with:
            java-version: '11'
            destribution: 'adopt'
      - name: Bild with Maven
        run: mvn -B -e verify
       
